### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by haha996** [KaiJin1995/fashionAI2018#1]
楼主您好，我对这个i任务特别感兴趣，也是真心的想学习您的优秀源码，可是苦于没有数据集。现在比赛结束官网上也不能下载了，我很想跑这个任务，您能否分享我一下数据集~

**Comment by KaiJin1995** [comment]
数据集后续天池会公开这个数据集的。
我这边电脑容量不太够，所以比赛完数据集就删了，就没办法给你了。
