### ISSUE TITLE
需要共享数据集

### ISSUE THREAD

**Issue by zhangwenhao123** [KaiJin1995/fashionAI2018#2]
你好，我报名晚了，无法下载数据集了，官方提供的数据集，还在可否分享以下到wendy_zhang@pku.edu.cn 。十分感谢

**Comment by KaiJin1995** [comment]
由于比赛结束后电脑空间不足就删掉了数据集，我这边没有了。
官方近期将会公开数据集，并且提供长期排行榜，你可以等两天去下载
